name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    outputs:
      changelog: ${{ steps.save-changelog.outputs.changelog }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    env:
      ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
      ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
      # Optional: skip postinstall rebuild in CI
      CI: true

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    # Cache electron + electron-builder
    - name: Cache electron and builder
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/.cache/electron
          ${{ github.workspace }}/.cache/electron-builder
        key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install Sharp Linux
      if: matrix.os == 'ubuntu-latest'
      working-directory: ./release/app
      run: |
        npm install --cpu=x64 --os=linux sharp

    - name: Install Sharp Windows
      if: matrix.os == 'windows-latest'
      working-directory: ./release/app
      run: |
        npm install --cpu=x64 --os=windows --libc=glibc sharp

    - name: Install Dependencies
      run: |
        npm ci --include=optional

    - name: Build
      run: |
        npm run package

    - name: Save Changelog
      id: save-changelog
      shell: bash
      run: |
        TAG=${{ github.ref_name }}
        OUTPUT=$(npm run version -- --dry-run --release-as ${TAG#v})
        echo "$OUTPUT"
        echo "changelog=$OUTPUT" >> "$GITHUB_OUTPUT"

    - name: Upload Windows artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: electron-dam-windows
        path: |
          release/build/*.exe
          release/build/*.blockmap
          release/build/latest*.yml

    - name: Upload Linux artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: electron-dam-linux
        path: release/build/*.AppImage
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          merge-multiple: true
          path: artifacts

      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: release/app

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ needs.build.outputs.changelog }}
          name: v${{ steps.package-version.outputs.current-version}}
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
